[tool.poetry]
name = "chia-blockchain"
version = "0.1.0"
description = "Chia blockchain full node, farmer, timelord, and wallet."
authors = ["Mariano Sorgente <mariano@chia.net>"]
license = "Apache License"
readme = "README.md"
keywords= ["chia", "blockchain", "node"]
homepage = "https://chia.net/"
packages = [{ include = "chia"}]

[tool.poetry.scripts]
chia = "chia.cmds.chia:main"
chia_daemon = "chia.daemon.server:main"
chia_wallet = "chia.server.start_wallet:main"
chia_full_node = "chia.server.start_full_node:main"
chia_harvester = "chia.server.start_harvester:main"
chia_farmer = "chia.server.start_farmer:main"
chia_introducer = "chia.server.start_introducer:main"
chia_crawler = "chia.seeder.start_crawler:main"
chia_seeder = "chia.seeder.dns_server:main"
chia_timelord = "chia.server.start_timelord:main"
chia_timelord_launcher = "chia.timelord.timelord_launcher:main"
chia_full_node_simulator = "chia.simulator.start_simulator:main"

[[tool.poetry.source]]
name = "chia"
url = "https://pypi.chia.net/simple/"

[tool.poetry.urls]
"Source" = "https://github.com/Chia-Network/chia-blockchain/"
"Changelog" = "https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = ">=3.7.2, <3.11"
aiofiles = "0.7.0"  # Async IO for files
aiohttp = "3.8.1"  # HTTP server for full node rpc
aiosqlite = "0.17.0"  # asyncio wrapper for sqlite, to store blocks
bitstring = "3.1.9"  # Binary data management library
blspy = "1.0.15"  # Signature library
chiabip158 = "1.1"  # bip158-style wallet filters
chiapos = "1.0.10"  # proof of space
chia_rs = "0.1.8"
chiavdf = "1.0.6"  # timelord and vdf verification
# TODO: when moving to click 8 remove the pinning of black noted below
click = "7.1.2"  # For the CLI
clvm = "0.9.7"
clvm_tools = "0.4.5"
clvm_tools_rs = "0.1.19"
colorama = "0.4.5"  # Colorizes terminal output
colorlog = "6.6.0"  # Adds color to logs
concurrent_log_handler = "0.9.19"  # Concurrently log and rotate logs
cryptography = "36.0.2"  # Python cryptography library for TLS - keyring conflict
dnspython = "2.2.0"  # Query DNS seeds
dnslib = "0.9.17"  # dns lib
filelock = "3.7.1"  # For reading and writing config multiprocess and multithread safely  (non-reentrant locks)
keyring = "23.6.0"  # Store keys in MacOS Keychain, Windows Credential Locker
# TODO: but...  keyrings_cryptfile goes 15 minutes without locking while this does in 75 seconds
"keyrings.cryptfile" = "1.3.4"  # Secure storage for keys on Linux (Will be replaced)
# See.cryptfile = "1.3.8"  # Secure storage for keys on Linux (Will be replaced)
# See https://github.com/frispete/keyrings.cryptfile/issues/15
packaging = "21.3"
pyyaml = "6.0"  # Used for config file format
setproctitle = "1.2.3"  # Gives the chia processes readable names
sortedcontainers = "2.4.0"  # For maintaining sorted mempools
typing-extensions = "4.3.0"  # typing backports like Protocol and TypedDict
watchdog = "2.1.9"  # Filesystem event watching - watches keyring.yaml
zstd = "1.5.0.4"


[tool.poetry.dev-dependencies]
aiohttp_cors = "^0.7.0"  # For blackd
# TODO: black 22.1.0 requires click>=8, remove this pin after updating to click 8
black = "21.12b0"
build = "^0.8"
coverage = "^6.4.1"
flake8 = "^5.0.4"
isort = "^5.10.1"
mypy = "0.971"
# ipython = "^8.2.0"  # For asyncio debugging
pre-commit = "^2.18.1"
py3createtorrent = "^1.1.0"
pyinstaller = "5.3"
pylint = "^2.15.0"
pytest = "^7.1.2"
pytest-asyncio = "^0.19.0"  # require attribute 'fixture'
pytest-monitor = "^1.6.4"
twine = "^4.0.0"
types-aiofiles = "^0.8.6"
types-click = "^7.1.8"
types-cryptography = "^3.3.18"
types-pkg_resources = "^0.1.3"
types-pyyaml = "^6.0.11"
types-setuptools = "^65.3.0"
pytest-xdist = "^2.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version =  ['py37', 'py38', 'py39']
include = '''
^/(
    [^/]*.py
    | (benchmarks|build_scripts|chia|tests|tools)/.*\.pyi?
)$
'''
exclude = ''
