[tool.poetry]
name = "chia-blockchain"
# see [tool.poetry-dynamic-versioning]
version = "0.1.0"
description = "Chia blockchain full node, farmer, timelord, and wallet."
authors = ["Mariano Sorgente <mariano@chia.net>"]
license = "Apache License"
readme = "README.md"
keywords= ["chia", "blockchain", "node"]
homepage = "https://chia.net/"
packages = [{ include = "chia"}]

[tool.poetry.scripts]
chia = "chia.cmds.chia:main"
chia_daemon = "chia.daemon.server:main"
chia_wallet = "chia.server.start_wallet:main"
chia_full_node = "chia.server.start_full_node:main"
chia_harvester = "chia.server.start_harvester:main"
chia_farmer = "chia.server.start_farmer:main"
chia_introducer = "chia.server.start_introducer:main"
chia_crawler = "chia.seeder.start_crawler:main"
chia_seeder = "chia.seeder.dns_server:main"
chia_timelord = "chia.server.start_timelord:main"
chia_timelord_launcher = "chia.timelord.timelord_launcher:main"
chia_full_node_simulator = "chia.simulator.start_simulator:main"
chia_data_layer = "chia.server.start_data_layer:main"
chia_data_layer_http = "chia.data_layer.data_layer_server:main"
chia_data_layer_s3_plugin = "chia.data_layer.s3_plugin_service:run_server"

[[tool.poetry.source]]
name = "chia"
url = "https://pypi.chia.net/simple/"
default = false
secondary = false

[tool.poetry.urls]
"Source" = "https://github.com/Chia-Network/chia-blockchain/"
"Changelog" = "https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = ">=3.7.2, <3.12"
aiofiles = "23.1.0"  # Async IO for files
aiohttp = "3.8.4"  # HTTP server for full node rpc
aiosqlite = "0.17.0"  # asyncio wrapper for sqlite, to store blocks
anyio = "3.6.2"
bitstring = "4.0.1"  # Binary data management library
blspy = "1.0.16"  # Signature library
boto3 = "1.26.111"  # AWS S3 for Data Layer S3 plugin
chiabip158 = "1.2"  # bip158-style wallet filters
chiapos = "1.0.11"  # proof of space
chia_rs = "0.2.5"
# TODO: presuming that https://github.com/Chia-Network/chia-blockchain/pull/13805 gets merged
chiavdf = "1.0.8"  # timelord and vdf verification
click = "8.1.3"  # For the CLI
clvm = "0.9.7"
clvm_tools = "0.4.6"  # Currying Program.to other conveniences
clvm_tools_rs = "0.1.30"  # Rust implementation of clvm_tools' compiler
colorama = "0.4.6"  # Colorizes terminal output
colorlog = "6.7.0"  # Adds color to logs
concurrent_log_handler = "0.9.20"  # Concurrently log and rotate logs
cryptography = "39.0.1"  # Python cryptography library for TLS - keyring conflict
dnslib = "0.9.23"  # dns lib
dnspython = "2.3.0"  # Query DNS seeds
filelock = "3.9.0"  # For reading and writing config multiprocess and multithread safely  (non-reentrant locks)
# TODO: required until we drop 3.7 support due to a conflict with flake8 < 6 and importlib-metadata
keyring = "23.9.3"  # Store keys in MacOS Keychain, Windows Credential Locker
packaging = "23.0"
psutil = "5.9.4"
pyyaml = "6.0"  # Used for config file format
setproctitle = "1.3.2"  # Gives the chia processes readable names
sortedcontainers = "2.4.0"  # For maintaining sorted mempools
typing-extensions = "4.5.0"  # typing backports like Protocol and TypedDict
watchdog = "2.2.0"  # Filesystem event watching - watches keyring.yaml
zstd = "1.5.4.0"

aiohttp_cors = { version = "^0.7.0", optional = true }
# TODO: black 22.1.0 requires click>=8, remove this pin after updating to click 8
black = { version = "23.3.0", optional = true }
build = { version = "^0.9", optional = true }
coverage = { version = "^7.1.0", optional = true }
diff-cover = { version = "^7.0.1", optional = true }
flake8 = { version = "^5.0.4", optional = true }
ipython = { version = "^8.6.0", python = ">=3.8", optional = true }
isort = { version = "^5.10.1", optional = true }
# TODO: but...  keyrings_cryptfile goes 15 minutes without locking while this does in 75 seconds
"keyrings.cryptfile" = { version = "1.3.9", optional = true }
mypy = { version = "^1.0", optional = true }
pre-commit = { version = "^2.20.0", optional = true }
py3createtorrent = { version = "^1.1.0", optional = true }
pyinstaller = { version = "5.8.0", optional = true }
pylint = { version = "^2.15.5", optional = true }
pytest = { version = "^7.2.0", optional = true }
pytest-asyncio = { version = "^0.20.1", optional = true }
pytest-cov = { version = "^4.0", optional = true }
pytest-monitor = { version = "^1.6.5", platform = "linux", optional = true }
pytest-xdist = { version = "^3.0.2", optional = true }
twine = { version = "^4.0.1", optional = true }
types-aiofiles = { version = "^22.0.1", optional = true }
types-cryptography = { version = "^3.3.23.1", optional = true }
types-pkg_resources = { version = "^0.1.3", optional = true }
types-pyyaml = { version = "^6.0.12.1", optional = true }
types-setuptools = { version = "^65.5.0.2", optional = true }

miniupnpc = { version = "2.2.2", source = "chia", optional = true }

[tool.poetry.extras]
dev = ["aiohttp_cors", "black", "build", "coverage", "diff-cover", "flake8", "ipython", "isort", "mypy", "pre-commit", "py3createtorrent", "pyinstaller", "pylint", "pytest", "pytest-asyncio", "pytest-cov", "pytest-monitor", "pytest-xdist", "twine", "types-aiofiles", "types-click", "types-cryptography", "types-pkg_resources", "types-pyyaml", "types-setuptools"]
upnp = ["miniupnpc"]
legacy_keyring = ["keyrings.cryptfile"]

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
dirty = true
pattern = "default-unprefixed"
format-jinja = "{% if distance == 0 %}{{ base }}{% else %}{{ base }}.dev{{ distance }}{% endif %}{% if dirty %}+dirty{% endif %}"
style = "pep440"
bump = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version =  ['py37', 'py38', 'py39', 'py310', 'py311']
include = '''
^/(
    [^/]*.py
    | (benchmarks|build_scripts|chia|tests|tools)/.*\.pyi?
)$
'''
exclude = ''
