os:
  macos: &os_macos
    name: macOS
    matrix: macos
    runs-on:
      arm: [macOS, ARM64]
      intel: [macos-latest]
    cibw-archs-macos:
      arm: arm64
      intel: x86_64
  linux: &os_linux
    name: Ubuntu
    matrix: ubuntu
    runs-on:
      arm: [ Linux, ARM64 ]
      intel: [ ubuntu-latest ]
  windows: &os_windows
    name: Windows
    matrix: windows
    runs-on:
      intel: [windows-latest]

arch:
  arm: &arch_arm
    name: ARM
    matrix: arm
  intel: &arch_intel
    name: Intel
    matrix: intel

python:
  c3_7: &python_3_7
    major-dot-minor: '3.7'
    cibw-build: 'cp37-*'
    matrix: '3.7'
  c3_8: &python_3_8
    major-dot-minor: '3.8'
    cibw-build: 'cp38-*'
    matrix: '3.8'
  c3_9: &python_3_9
    major-dot-minor: '3.9'
    cibw-build: 'cp39-*'
    matrix: '3.9'
  c3_10: &python_3_10
    major-dot-minor: '3.10'
    cibw-build: 'cp310-*'
    matrix: '3.10'

exclude: &exclude
  - os:
      matrix: windows
    arch:
      matrix: arm
  - os:
      matrix: macos
    python:
      matrix: '3.7'
    arch:
      matrix: arm
  - os:
      matrix: macos
    python:
      matrix: '3.8'
    arch:
      matrix: arm

matrix:
  os:
    - *os_macos
    - *os_linux
    - *os_windows
  python:
    - *python_3_7
    - *python_3_8
    - *python_3_9
    - *python_3_10
  arch:
    - *arch_arm
    - *arch_intel
  exclude: *exclude
