name: 🚨 pre-commit

on:
  pull_request:
  push:
    branches:
      - 'long_lived/**'
      - main
      - 'release/**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
  cancel-in-progress: true

jobs:
  library:
    uses: ./.github/workflows/library.yml

  pre-commit:
    name: pre-commit ${{ matrix.os.name }}
    needs: library
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.library.outputs.library).matrix }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v2.0.3
