name: test

on:
  push:
    branches:
    - long_lived/**
    - main
    - release/**
    tags:
    - '**'
  pull_request:
    branches:
    - '**'
  workflow_dispatch: null

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}--${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
  cancel-in-progress: true

jobs:
  configure:
    name: Configure matrix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Generate matrix configuration
        id: configure
        run: |
          python tests/build-job-matrix.py --per directory --verbose > matrix.json
          cat matrix.json
          echo ::set-output name=configuration::$(cat matrix.json)
          echo ::set-output name=steps::$(cat some.json)

    outputs:
      configuration: ${{ steps.configure.outputs.configuration }}

  macos:
    uses: ./.github/workflows/test-single.yml
    needs: configure
    with:
      emoji: 🍎
      matrix: macos
      name: macOS
      file_name: macos
      concurrency_name: macos
      configuration: ${{ needs.configure.outputs.configuration }}
      runs-on: macos-latest
  ubuntu:
    uses: ./.github/workflows/test-single.yml
    needs: configure
    with:
      emoji: 🐧
      matrix: ubuntu
      name: Ubuntu
      file_name: ubuntu
      concurrency_name: ubuntu
      configuration: ${{ needs.configure.outputs.configuration }}
      runs-on: ubuntu-latest
  windows:
    uses: ./.github/workflows/test-single.yml
    needs: configure
    with:
      emoji: 🪟
      matrix: windows
      name: Windows
      file_name: windows
      concurrency_name: windows
      configuration: ${{ needs.configure.outputs.configuration }}
      runs-on: windows-latest

  coverage:
    name: Coverage
    runs-on: ${{ matrix.os.runs-on }}
    needs:
      - macos
      - ubuntu
      - windows
    strategy:
      fail-fast: false
      matrix:
        os:
          - emoji: 🐧
            matrix: ubuntu
            name: Ubuntu
            runs-on: ubuntu-latest
        python:
          - name: '3.9'
            action: '3.9'
            apt: '3.9'
            install_sh: '3.9'
            matrix: '3.9'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage-reports
          path: coverage-data

      - name: Set up ${{ matrix.python.name }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python.action }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install coverage diff-cover

      - name: Coverage Processing
        if: always()
        run: |
          # skip windows until https://github.com/nedbat/coveragepy/issues/991 is resolved
          rm coverage-data/*.tests_windows_* coverage-data/.*.tests_windows_*
          mkdir coverage-report
          coverage combine --data-file coverage-reports/.coverage coverage-data/

      - name: Coverage report
        run: |
          coverage xml --data-file coverage-reports/.coverage -o coverage-reports/coverage.xml
          coverage html --data-file coverage-reports/.coverage --directory coverage-reports/html/
          coverage report --rcfile=.coveragerc --ignore-errors --show-missing | tee coverage-reports/coverage-stdout
          diff-cover --compare-branch=${{ fromJSON(format('[{0}, {1}]', toJSON(github.event.before), toJSON(format('origin/{0}', github.base_ref))))[github.base_ref != ''] }} coverage-reports/coverage.xml |  tee coverage-reports/diff-cover-stdout

      - name: Publish coverage reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: coverage-reports/*
          if-no-files-found: error
